### ISSUE TITLE
G3W questions and issues

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#106]
- [x] the original intention was to have some sort of syncing for back-end QGIS project files - was this never implemented? If so is the only way to update a project to overwrite it by uploading through the web interface?

- [x] what was the intended workflow with the staging project?

- [x]  The G3W 'file manager' application shows a blank screen, looks like it needs fixing...

**Comment by NyakudyaA** [comment]
> * [ ]  the original intention was to have some sort of syncing for back-end QGIS project files - was this never implemented? If so is the only way to update a project to overwrite it by uploading through the web interface?

This was never implemented because when a user uploads a project to the g3wsuite, there is logic to reads the project file to determine the layer structure etc and store this information on the DB, uploading through the UI seems a logical thing. Also if the project changes, things like styles we can also access the volume of the cluster using 
```
kubectl exec -n workspace-name container-name -- /bin/bash
```
> 
>     * [ ]  what was the intended workflow with the staging project?
The staging was meant to be a testing place for anything that we don't understand about the suite.

> 
>     * [x]   The G3W 'file manager' application shows a blank screen, looks like it needs fixing...

**Comment by gubuntu** [comment]
thanks @NyakudyaA
