### ISSUE TITLE
9. describe land use history

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#50]
9. LAND USE HISTORY:
(If known, give a brief summary of past/historical land use(s), resource uses and landscape dynamics of each zone of the proposed biosphere reserve).

ref biosphere_reserve_nomination_form_2013_en.pdf

**Comment by seabilwe** [comment]
Found a masters research done at Wits on the LULC history in the WBR
Link: https://drive.google.com/file/d/1zqsrwZQwFO6rNh2hyz8WnNZDv7zBNE_v/view?usp=sharing 
Using some of the references used in the article

**Comment by seabilwe** [comment]
Link to land use history document: https://docs.google.com/document/d/1Agca25pclG1o9db5ZQCeETNhoRkYdXHdC3j6Oc1rMa8/edit#

**Comment by seabilwe** [comment]
##Land Use History Description

The Waterberg District is a subtropical savanna eco-region with important biodiversity values and is home to the Waterberg Biosphere Reserve. The region has several headwaters in the notoriously water scarce province. The four main rivers are the Lephalala, Mokolo, Matlabas and Mogalakwena Rivers. The rivers are modified and vulnerable to changes from intense agriculture, urban spread, mining activities and atmospheric deposition from fossil fuel-based power generation.
The Waterberg region is one of the remaining regions that has not been highly exploited. The region has high biodiversity and it is less populated of because of its remoteness, inaccessibility and the condition and type of soil. The main land use practice in the region is crop farming (both subsistence and commercial), which takes place along the riverbanks. 
Besides agricultural practices, the area has experienced fast urban and mine (as it holds the potential coalfields to supply coal for fossil energy generation) growth over the years, which raises concerns on the quality of water, aquatic species and ecosystem functionality.
The alteration of cropland to game farming caused re-vegetation which could influence the ecological functioning of both aquatic and terrestrial ecosystems in the region. Cropland, game farming and built up expansion land use activities threaten head-water streams within the Waterberg region. Croplands have considerably decreased due to weather conditions and poor-nutrient soils mostly. These activities have brought about changes to the landscape, habitat destruction, biological invasion, and increased water resource stressed. 
The head-water streams of the Waterberg District provide ecosystem services, such as drinking water purification, aquatic habitat and rapid processing and nutrient uptake, which can limit the accumulation of phosphorous and nitrogen to the downstream aquatic and riparian ecosystems. 
The streams are affected by natural and anthropogenic processes, while the latter such as agricultural activities, mining, and urban development is increasingly recognized as a dominant force in landscape modification. These streams are vulnerable to land use impacts than larger, higher-order streams due to their abundance and small size.
The changes taking place in the head-water streams affects the ecological integrity of freshwater ecosystems of the Waterberg region as a whole. Some of the head-water streams of these river catchments (the Mokolo, Mogalakwena for example) originated outside the biosphere reserve. The head-water streams of Mokolo and Mogalakwena are vulnerable to land degradation, before flowing into the biosphere reserve as they originate outside of the biosphere reserve (i.e. the WBR).

**Comment by gubuntu** [comment]
where are the references you mention?

**Comment by seabilwe** [comment]
@gubuntu Reference list

- De Klerk, A., 2004. The Waterberg Biosphere Reserve: a land use model for ecotourism development (Doctoral dissertation, University of Pretoria).
- De Klerk, A. and De Klerk, A.R., 2011. Baseline study of the Mokolo and Lephalala rivers in the Waterberg area.
- Belsoy, J., Korir, J. and Yego, J., 2012. Environmental impacts of tourism in protected areas. Journal of Environment and Earth Science, 2(10), pp.64-73.
- Mundalamo, T.D., 2019. Characterizing historic land use and land cover change using landsat earth obsrvation data in the Waterberg biosphere reserve (Doctoral dissertation).
