### ISSUE TITLE
14. describe conservation function

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#54]
14. CONSERVATION FUNCTION

14.1. At the level of landscapes and ecosystems (including soils, water and climate):

- [x] 14.1.1 Describe and give the location of ecosystems and/or land cover types of the biosphere reserve.
- [x] 14.1.2 Describe the state and trends of the ecosystems and/or land cover types described above and the natural and human drivers of the trends.
- [x] 14.1.3 What kind of protection regimes (including customary and traditional) exist for the core area(s) and the buffer zone(s)?
- [x] 14.1.4 Which indicators or data are used to assess the efficiency of the actions/strategy used?

14.2 At the level of species and ecosystem diversity:

- [x] 14.2.1 Identify main groups of species or species of particular interest for the conservation objectives, especially those that are endemic to this biosphere reserve, and provide a brief description of the communities in which they occur.
- [x] 14.2.2 What are the pressures on key species? In other words: what are the threats (example unsustainable management of forest), their immediate causes (drivers of change like forest change or habitat change), their underlying causes (example overgrazing, fire, pollution), and the main driving forces (example: economic, political, social, external, etc.) and the area(s) concerned?
- [x] 14.2.3 What kind of measures and indicators are currently used, or planned to be used to assess both species groups and the pressures on them? Who undertakes this work, or will do so in the future?
- [x] 14.2.4 What actions are currently undertaken to reduce these pressures?
- [x] 14.2.5 What actions do you intend to take to reduce these pressures?

14.3. At the level of genetic diversity:

- [ ] 14.3.1 Indicate species or varieties that are of importance (e.g. for conservation, medicine, food production, agrobiodiversity, cultural practices etc).
- [ ] 14.3.2 What ecological, economic or social pressures or changes may threaten these species or varieties?
- [ ] 14.3.3 What indicators, at the level of the species, are used, or will be used, to assess the evolution of population status and associated use?
- [ ] 14.3.4 What measures will be used to conserve genetic diversity and practices associated with their conservation?

ref biosphere_reserve_nomination_form_2013_en.pdf

**Comment by zacharlie** [comment]
# More Information Required

Much of the ecosystem description is avialable from the Waterberg District Bioregional Plan (Draft 2016), which should likely be supplied as an annex.

Very little resource is available for describing the intended management plans outlined as expected to be described in sections 14.2 and 14.3

Additionally, much of the questions from 14.3 ask for the same information, however it is expected that this should be at a level of detail unavailable from the current resources.

**Comment by zacharlie** [comment]
## 14.1.1 Describe and give the location of ecosystems and/or land cover types of the biosphere reserve.

<overlay analysis awaiting completion of zonation /><include NBAs/ ESA|CBAs/ Wetlands />

2018 National Biodiversity Assessment data outlines a number of Biodiversity areas and their conservation status.

Whilst the vast majority of the study area is covered by Central Bushveld type bioregions, there are concentrations of endemic Mesic Highveld Grassland, with adiditonal minor areas of Mopane Bioregion and Alluvial Vegetation.

The following table outlines the coverage of the various biomes within the study area and their relative coverage

| Name                                     | Biome             | Bioregion                          | Threat Status | Endemic                 | Ha           | Coverage |
|------------------------------------------|-------------------|------------------------------------|---------------|-------------------------|--------------|----------|
| Central Sandy Bushveld                   | Savanna           | Central Bushveld Bioregion         | Least Concern | Endemic                 | 692569.8180  | 13%      |
| Dwaalboom Thornveld                      | Savanna           | Central Bushveld Bioregion         | Least Concern | Likely not endemic      | 531848.9290  | 10%      |
| Dwarsberg-Swartruggens Mountain Bushveld | Savanna           | Central Bushveld Bioregion         | Least Concern | Likely not endemic      | 2340.9440    | 0%       |
| Limpopo Ridge Bushveld                   | Savanna           | Mopane Bioregion                   | Least Concern | Likely not endemic      | 1702.9662    | 0%       |
| Limpopo Sweet Bushveld                   | Savanna           | Central Bushveld Bioregion         | Least Concern | Likely not endemic      | 1021793.3181 | 19%      |
| Loskop Mountain Bushveld                 | Savanna           | Central Bushveld Bioregion         | Least Concern | Endemic                 | 6596.0367    | 0%       |
| Madikwe Dolomite Bushveld                | Savanna           | Central Bushveld Bioregion         | Least Concern | Likely not endemic      | 39215.8236   | 1%       |
| Makhado Sweet Bushveld                   | Savanna           | Central Bushveld Bioregion         | Least Concern | Endemic                 | 307779.2331  | 6%       |
| Mamabolo Mountain Bushveld               | Savanna           | Central Bushveld Bioregion         | Least Concern | Endemic                 | 20056.4948   | 0%       |
| Musina Mopane Bushveld                   | Savanna           | Mopane Bioregion                   | Least Concern | Likely not endemic      | 20585.6694   | 0%       |
| Pilanesberg Mountain Bushveld            | Savanna           | Central Bushveld Bioregion         | Least Concern | Endemic                 | 12903.3308   | 0%       |
| Polokwane Plateau Bushveld               | Savanna           | Central Bushveld Bioregion         | Least Concern | Endemic                 | 86551.8155   | 2%       |
| Poung Dolomite Mountain Bushveld         | Savanna           | Central Bushveld Bioregion         | Least Concern | Endemic                 | 5762.5181    | 0%       |
| Roodeberg Bushveld                       | Savanna           | Central Bushveld Bioregion         | Least Concern | Unsure - needs research | 525932.0073  | 10%      |
| Springbokvlakte Thornveld                | Savanna           | Central Bushveld Bioregion         | Vulnerable    | Endemic                 | 518775.8326  | 10%      |
| Strydpoort Summit Sourveld               | Grassland         | Mesic Highveld Grassland Bioregion | Least Concern | Endemic                 | 7610.8891    | 0%       |
| Subtropical Alluvial Vegetation          | Azonal Vegetation | Alluvial Vegetation                | Least Concern | Likely not endemic      | 18552.3056   | 0%       |
| Waterberg-Magaliesberg Summit Sourveld   | Grassland         | Mesic Highveld Grassland Bioregion | Least Concern | Endemic                 | 50096.4905   | 1%       |
| Waterberg Mountain Bushveld              | Savanna           | Central Bushveld Bioregion         | Least Concern | Endemic                 | 882361.5752  | 16%      |
| Western Sandy Bushveld                   | Savanna           | Central Bushveld Bioregion         | Least Concern | Unsure - needs research | 583819.3066  | 11%      |
| Zeerust Thornveld                        | Savanna           | Central Bushveld Bioregion         | Least Concern | Likely not endemic      | 15953.1579   | 0%       |

![Biomes](https://user-images.githubusercontent.com/64078329/98790646-b3390c80-240c-11eb-9772-fd2239198f3d.png)


![Endemism](https://user-images.githubusercontent.com/64078329/98790656-b7652a00-240c-11eb-80fa-cecb038d9bda.png)


![Threats](https://user-images.githubusercontent.com/64078329/98790672-bd5b0b00-240c-11eb-9b2b-4fb8122a115d.png)

See also: Waterberg District Bioregional Plan (Draft 2016) - 2.4 Vegetation and Threatened Ecosystems

> Note: could possibly include aggregation of national landover coverage by type, however I think this is a significant processing requirement for a result which adds little value and is a large inclusion which may degrade the results. Referencing the existing nomination landcover and vegetation maps should be sufficient.

**Comment by zacharlie** [comment]
## 14.1.2 Describe the state and trends of the ecosystems and/or land cover types described above and the natural and human drivers of the trends.

A broad outline of the landcover change trends was produced with the [trends.earth QGIS plugin](https://plugins.qgis.org/plugins/LDMP/) produced by Conservation International, which analyses data available via the Google Earth Engine API.

The resulting data is a Land Degradation Neutrality, Sustainable Development Goal (SDG) Target 15.3 index.

More information on the mechanics of the trend calculation and the source datasets are available from the [trends.earth](http://trends.earth) website.

The complete area of interest for the study was analysed for the period of 2001-2015 (using the default plugin setings). A full outline of the results is available from the conservation_function/wbr_trends.ods spreadsheet, with the core outcomes outlined in the following table:

| Landcover Trend         | Area (sq km) | Percent of total land area |
|-------------------------|--------------|----------------------------|
| Total land area:        | 53 542.9     | 100.00%                    |
| Land area improved:     | 7 921.5      | 14.79%                     |
| Land area stable:       | 29 674.4     | 55.42%                     |
| Land area degraded:     | 15 939.0     | 29.77%                     |
| Land area with no data: | 7.9          | 0.01%                      |

A distinct concentration of improved areas is from the Worth Eastern part of the region, whilst the South West areas contain a significant portion of degraded areas identified by the trend analysis. Patterns may suggest strong impact of human activity as drivers of degradation (with degradation surrounding settlements), however the impact across largest areas seems to be driven by environmental changes and perhaps larger scale activities which are less urban in nature, such as mining and agriculture.

![Trend](https://user-images.githubusercontent.com/64078329/98790790-dcf23380-240c-11eb-8afd-73df301e877f.png)

**Comment by zacharlie** [comment]
## 14.1.3 What kind of protection regimes (including customary and traditional) exist for the core area(s) and the buffer zone(s)?

Core areas are national protected areas (private game reserves/ national parks) protected by South African National law under the National Environmental Management: Protected Areas Act. Buffer and transition zones do not have the legal protections afforded to core areas and are managed via governance models that are outlined in the [institutional aspects](https://github.com/kartoza/WBR-SEMP/issues/56). Buffer zones are expected to have limited activity as they are considered by reginoal planning units to minimise the negative impact of human activities.

**Comment by zacharlie** [comment]
## 14.1.4 Which indicators or data are used to assess the efficiency of the actions/strategy used?

<needs more information />

The Biosphere reserve is incorporated into the UNESCO Man and the Biosphere programme and utilises a cooperative governance model with agencies spanning regional, national and international public and private organisations. Multiple programs ensure the ongoing study and monitoring of numerous indicators.

The primary monitoring mechanisms which are intended to be implmented are outlined in the Waterberg District Bioregional Plan, which utilise the following core indicators:

- Percentage and area (hectares) of Critical Biodiversity Areas and Ecological Support Areas that are contained within conservation orientated zones within Spatial Development Frameworks, Land Use Schemes and Environmental Management Frameworks. For this purpose, conservation orientated zones are defined as areas where the primary purpose is conservation or where there are significant restrictions on allowable land-uses.
- Percentage and area (hectares) of Critical Biodiversity Areas and Ecological Support Areas that are under some form of conservation management (including both formal protection and conservation stewardship agreements).
- Percentage and area (hectares) of Critical Biodiversity Areas and Ecological Support Areas where subdivision has been approved or where increased development rights have been granted.
- Percentage and area (hectares) of Critical Biodiversity Areas and Ecological Support Areas where appropriate biodiversity management interventions have been applied (e.g. clearing of invasive alien species, biodiversity management plans).
- Percentage and area (hectares) of Critical Biodiversity Areas and Ecological Support Areas that have been severely or irreversibly modified due to various land-use changes.
- Percentage and area (hectares) of Critical Biodiversity Areas and Ecological Support Areas that are in a natural or near-natural state (key aspects would be level of invasive alien vegetation infestation, level of degradation due to overgrazing, sand mining or dumping etc.).
- Percentage and area (hectares) of Critical Biodiversity Areas and Ecological Support Areas that have been rehabilitated to an ecological condition (viz. land management objective, Table 10) consistent with CBA2 or ESA1 areas.

**Comment by zacharlie** [comment]
## 14.2.1 Identify main groups of species or species of particular interest for the conservation objectives

Summary of important species for conservation outlined in https://github.com/kartoza/WBR-SEMP/issues/60

Excerpt from Waterberg District Bioregional Plan (Draft 2016):

- Plants: Species information was obtained from SANBI, including from database searches and literature sources (EMF, 2010b). Sixty-four plant species of special concern are found within the Waterberg District. Twenty-two of the 64 species are threatened. Three are Critically Endangered, namely: Euphorbia clivicola, Gasteria disticha and Orbea elegans (potentially extinct). Three are Endangered, including Brachystelma gerrardii, Delosperma macellum and Encephalartos eugene-maraisii. Sixteen species are Vulnerable, namely Brachycorythis conica, Ceropegia stentiae, Corchorus psammophilus, Cucumis humifructus, Cullen holubii, Cyphostemma hardyi, Elytrophorus globularis, Eulophia coddii, Jamesbrittenia bergae, Ledebouria atrobrunnea, Marsilea farinosa subsp. arrecta, Oryza longistaminata, Prunus africana and Sartidia jucunda. Of the 64 species, 43 are not threatened nationally, but are of local concern. These species are listed as Near Threatened (12), Critically Rare (1), Rare (16) or Declining (14) (EMF, 2010b).
- Mammals: Forty-five mammal species of special concern inhabit the Waterberg District. A total of 15 species are listed as Critically Endangered, Endangered or Vulnerable. Those afforded protection in protected areas, game reserves or in private breeding programmes include the Endangered tsessebe (Damaliscus lunatus), the Endangered black rhino (Diceros bicornis), the Vulnerable roan antelope (Hippotragus equinus), the Vulnerable sable antelope (Hippotragus niger), the Vulnerable cheetah (Acinonyx jubatus), the Endangered African wild dog (Lycaon pictus), the Vulnerable elephant (Loxodonta africana), the Vulnerable hippopotamus (Hippopotamus amphibious) and the Vulnerable lion (Panthera leo). The remaining species have a restricted distribution range and are not afforded such protection, namely the Critically Endangered short-eared trident bat (Cloeotis percivali), the Vulnerable botswana long-eared bat (Laephotis botswanae), the Vulnerable peak-saddle horseshoe bat (Rhinolophus blasii), the Vulnerable Juliana’s golden mole (Amblysomus julianae), the Vulnerable giant rat (Cricetomys gambianus) and the Vulnerable pangolin (Manis temminckii) (EMF, 2010b).
- Reptiles: The Vulnerable Nile crocodile (Crocodylus niloticus) and Vulnerable African rock python (Python sebae natalensis), and the Near Threatened Muller’s velvet gecko (Homopholis mulleri), are distributed within the Waterberg District (EMF, 2010b). The Kalahari purple-glossed snake (Amblyodipsas ventrimaculata) was recorded near Vaalwater, and occurs nowhere else in South Africa (River Health Programme, 2006).
- Birds: Three Important Bird Areas (IBAs) of South Africa lie within the Waterberg District, known as the Waterberg System, Nyl River Floodplain and the Northern Turf Thornveld (also see Section 2.2). As a result, bird diversity is high, with 21 bird species of special concern that are classified as Critically Endangered, Endangered or Vulnerable. The variety of ecosystems within the Waterberg District provides habitat for these birds, ranging from rivers, wetlands and mountainous areas, to savannas, forests and grasslands. The Critically Endangered Cape parrot (Poicephalus robustus) inhabits forest and is endemic to South Africa. The bittern (Botaurus stellaris) is also Critically Endangered and inhabits lowland swamps and wetlands. Some of the species classified as Endangered include the Cape vulture (Gyps coprotheres), white backed vulture (Gyps africanus), saddle-billed stork (Ephippiorhynchus senegalensis) and Pel’s fishing owl (Scotopelia peli). Vulnerable species include, for example, the blue crane (Anthropoides paradiseus), African finfoot (Podica senegalensis), African grass Owl (Tyto capensis), bateleur (Terathopius ecaudatus), kori bustard (Ardeotis kori) and the martial eagle (Polemaetus bellicosus) (EMF, 2010b; EMF, 2010c).
- Amphibian: The Giant bullfrog (Pyxicephalus adspersus) is Near Threatened and relies on temporary wetlands and dams in the Waterberg District (EMF, 2010b).

**Comment by zacharlie** [comment]
## 14.2.2 What are the pressures on key species?

Key pressures for all species include external factors such as climate change and habitat destruction. Due to the regional climate, water availability and quality is of critical importance and disruptions impact greatly on biodiversity in many ecosensitive areas. The Waterberg District Bioregional Plan outlines important aspects for the protection of water processes and climate change addaptation/ mitigation as follows:

- Dolomitic aquifers act as sponges for rainfall providing valuable subterranean water reservoirs. It is essential that land-use in these landscapes does not interrupt or degrade recharge of these aquifers.
- Wetland systems play a keystone regulatory role in the hydrology of the Waterberg District by:
  1. Absorbing and storing freshwater
  2. Maintaining and moderating the flow of rivers
  3. Improving water quality
  4. Maintaining the ecological and structural integrity of river systems
  5. Buffering surrounding landscapes from flooding
- The high southern and eastern mountains of the Waterberg are high priority water production areas, referred to as strategic water source areas. Much of the high-quality river flow in the WDM originates in this area.
- Corridors and connectivity: Maintaining connectivity is critical for long-term persistence of biodiversity in the face of on-going climate change. Connected natural landscapes allow biodiversity to respond and adapt to the impacts of climate change. Maintaining landscape connectivity is a major action that the Waterberg District can make to mitigate climate change impacts within the WDM, Limpopo Province and South Africa as a whole. Mountains, ridges and rivers, including wetland systems, represent important natural corridors in the Waterberg District. For example, the Waterberg and satellite hills are an important bio-geographical corridor with unique biodiversity (EMF, 2010b).
- Climate change refugia: Climate change refugia are local areas with significantly different or moderated local or microclimates, or a diversity of microclimates that provide species with local refuges in the face of regional climate changes. In the Waterberg these include high altitude grasslands, kloofs and south facing mountain slopes as well as the High Diversity Areas defined in the Waterberg EMF. There are zones of high species diversity; high topographic diversity; and, strong biophysical gradients (e.g. altitude, rainfall or temperature) that meet the criteria for climate change refuge areas.
- Areas for minimizing climate change impacts on society: Climate change is likely to result in significant increases in climate variability. In the urban context, perhaps the most important consequence is an increase in the likelihood of extreme flood events. Protection of intact natural habitat (especially wetlands, floodplains and intact riparian habitat) is extremely important for reducing the magnitude of flood events as these areas play an important role in regulating hydrological processes, such as storm water runoff. In addition, these areas (especially floodplains) are extremely high risk for communities living in these areas. Ensuring that infrastructure and agricultural development is avoided, where possible, in high-risk areas will reduce the long term impact of climate change, particularly on poor communities.

The Waterberg District Bioregional Plan additionally outlines threats to many regions including the IBAs as follows:

- Mining poses a threat to some areas within these IBAs particularly the Nyl River system.
- Uncontrolled fires are a problem for all the IBAs. In some instances, a lack of fire can lead to bush encroachment, loss of grassland as well as moribund grassland patches.
- Poisoning of vultures remains a threat. One poisoning incident has the potential to kill large numbers of vultures.
- Collisions with radio towers, television towers and powerlines are a threat to large bodied birds and have caused substantial vulture mortality in the past.
- Loss of cultivated lands. Fallow crop fields are important over-winter habitats for blue cranes in the Alma area and yellow-throated sandgrouse in the Northern Turf Thornveld areas.
- The Nyl River Floodplain is reliant on rain run-off from the eastern and southern Waterberg. Impoundments and abstraction of water already significantly reduce river flow entering the floodplain, which reduces the ecological integrity of the ecosystem. Rivers feeding the wetland are also impacted by small-scale damming; construction of weirs; sand mining; and, destruction of wetlands and riparian areas. These impacts alter the water quality entering the system and flooding regime that drives this system.

Additional details on particular threats in specific areas can be outlined by the descriptions available for the Important Bird Areas (IBAs) within the study area:

- [The Waterberg System](https://www.birdlife.org.za/iba-directory/waterberg-system/): There are surprisingly few threats to this large IBA. Agricultural activities are declining and large areas of agricultural land have been converted to game farms. Uncontrolled fires are probably the biggest threat to the trigger species and their habitats. The poisoning of vultures remains a threat; a single incident can potentially kill large numbers of these birds. A few applications to mine in the IBA have been submitted. However, the Waterberg is not an area of high mineral content and mining should not be a threat to this IBA. Collisions with radio and television towers as well as power lines have caused substantial vulture mortality. A number of large dams occur in the IBA. Although the management of these dams does not directly affect the Waterberg System IBA, it does have an impact on the Nyl River Floodplain IBA (SA008), as the Waterberg is within the catchment of the Nyl River. These two IBAs are therefore interconnected.

- [Northern Turf Thornveld](https://www.birdlife.org.za/iba-directory/northern-turf-thornveld/): The Yellow-throated Sandgrouse population is relatively healthy. The birds have adapted to foraging in fallow fields over the past few years because much of their natural habitat has been transformed into agricultural land, especially through the establishment of centre-point irrigation schemes. There are a number of mines in the area and it is a concern that the footprint of these mines is increasing.

- [Pilansberg National Park](https://www.birdlife.org.za/iba-directory/pilansberg-national-park/): The IBA is relatively close to the large urban areas of Gauteng and Rustenburg. There are many roads, fences and infrastructure for electricity supply that pose potentially deadly threats, especially to large and wide-roaming birds such as raptors, cranes and bustards. It may not be sufficient to provide a place of refuge inside the park in order to conserve the local populations of these species. Pilanesberg National Park is bordered by quite large low-income human settlements. The poor socio-economic situation in these areas raises the risk of potential poaching incidents, either for food or to satisfy the increasing demand for wildlife products on the black market.

- [Nylsvley/ Nyl River Floodplain](https://www.birdlife.org.za/iba-directory/nyl-river-floodplain/): The system is reliant on rain falling in the Waterberg (IBA SA007) and inundating the plain. Any impoundment or disturbance to the flow of the handful of rivers that contribute to the floodplain could seriously impact Nylsvley. The river is subjected to small-scale damming, dykes and the extraction of sand, all of which may alter the delicate flooding regime that drives this dynamic system. Another threat to the IBA is the large amount of water extracted from the floodplain by centre-pivot irrigation schemes. Uncontrolled fires are a problem, as demonstrated by the fire that devastated large parts of the floodplain in 2013. On the other hand, regular block burns are not conducted sufficiently on the floodplain, which is leading to the encroachment of bush and the loss of grassland, as well as some grassland patches becoming moribund. Part of the reason for this is that the wetland remains wet in winter, making it difficult to conduct burns in it. In 2013–2014 a number of applications were received to mine on the floodplain. If approved, mines could have a detrimental impact on the trigger species in the IBA.

**Comment by zacharlie** [comment]
## 14.2.3 What kind of measures and indicators are currently used?

Measures are outlined in the Waterberg District Bioregional Plan as described in 14.1.4

**Comment by zacharlie** [comment]
## 14.2.4 What actions are currently undertaken to reduce these pressures?

- [The Waterberg System](https://www.birdlife.org.za/iba-directory/waterberg-system/): Protected areas within the IBA are Marakele National Park, D’Nyala Nature Reserve, Entabeni Nature Reserve, Doorndraai Nature Reserve and Hans Strijdom Nature Reserve. Welgevonden Private Nature Reserve has also applied to receive formal protection as a nature reserve. These reserves are generally well managed, although some of them lack funding and staff. Unfortunately some of the vulture colonies fall outside Marakele National Park and extending the park’s boundary to rectify this situation should be investigated. BirdLife Northern Gauteng has become the Local Conservation Group for this IBA and will assist with bird-monitoring projects in the IBA, such as SABAP2, CWAC and ringing.

- [Northern Turf Thornveld](https://www.birdlife.org.za/iba-directory/northern-turf-thornveld/): No formal protected areas occur within the IBA. More monitoring is needed to determine the population status of Yellow-throated Sandgrouse and especially the threats that impact on this species. The status of other trigger species within the IBA must also be studied in more detail. Based on this analysis, the status of this IBA should be re-evaluated.

- [Pilansberg National Park](https://www.birdlife.org.za/iba-directory/pilansberg-national-park/): The establishment of a national park in the Pilanesberg was first suggested in 1969. When Sun City was built in 1978 a park became viable from a tourism perspective and Pilanesberg National Park came into being in 1980. Game was purchased for the ‘Operation Genesis’ re-introduction, for which WWF-SA provided a substantial portion of the funding. Since South Africa became a democracy in 1994, the park has been controlled by North West Parks. This IBA is a formally protected provincial nature reserve.

- [Nylsvley/ Nyl River Floodplain](https://www.birdlife.org.za/iba-directory/nyl-river-floodplain/): The Nylsvley Nature Reserve is located within the IBA and was established in 1967. It is also a Ramsar site. The reserve is well managed and has a management plan, although there is not enough funding or staff to implement it. The management plan also does not address issues relating to bird conservation in the reserve, for example the management of the grasses in the wetland. It is hoped that in 2015 an area east of Mokopane will be declared the Grootvaley Protected Environment. A concerted effort should be made to obtain Protected Environment status for the area outside the nature reserve.

**Comment by zacharlie** [comment]
## 14.2.5 What actions do you intend to take to reduce these pressures?

The current Waterberg Disrict Bioregional Plan outlines the following monitoring plan:

The Waterberg District Municipality is the primary implementing agent of the Waterberg District Bioregional Plan, and is therefore responsible for monitoring, reviewing and updating the Bioregional Plan. Reviewing and updating the systematic biodiversity plan on which the Bioregional Plan is based is the responsibility of the Limpopo Department of Economic Development, Environment and Tourism (LEDET). Because there are numerous issues requiring joint planning (e.g. shared ecosystems, rivers and catchments), it would be efficient to establish an inter-agency structure for coordinating the implementation, monitoring, reviewing and updating of the Waterberg District Bioregional Plan. Alternatively, these activities would need to be undertaken independently by the Waterberg District Municipality. The following is recommended:

- The establishment of an appropriate inter-agency structure to coordinate the implementation, monitoring, reviewing and updating of the Bioregional Plan, namely the Waterberg District Bioregional Plan Coordination Committee.
- The on-going evaluation of its use in land-use planning and decision-making.
- The review of, and if necessary, revision of the underlying systematic biodiversity plan at least every five years.
- The update of the published Waterberg District Bioregional Plan at least every five years.

**Comment by zacharlie** [comment]
## 14.3.1 Indicate species or varieties that are of importance.

Species of importance for conservation are outlined in 14.2.1

Other species of importance for activities such as medicine, food production, agrobiodiversity, cultural practices etc are unkown at this time.

**Comment by zacharlie** [comment]
## 14.3.2 What ecological, economic or social pressures or changes may threaten these species or varieties?

Answered _14.2.2 What are the pressures on key species_. No further information is currently available for distinct species of special importance.

**Comment by zacharlie** [comment]
## 14.3.3 What indicators, at the level of the species, are used, or will be used, to assess the evolution of population status and associated use?

For species of importance for conservation, the [Global Biodiversity Information Facility](https://www.gbif.org/), or GBIF program, provides an accessible database of spatial species observations and occurences. Additional species information data is periodically obtained from SANBI in the form of database searches and literature sources as detailed in the processes outlined in the Waterberg District Bioregional Plan.

For other species of importance, no further information is available at this time.

**Comment by zacharlie** [comment]
## 14.3.4 What measures will be used to conserve genetic diversity and practices associated with their conservation?

The extension of the Waterberg Biosphere Reserve entails the ongoing cooperation between many entities and a commitment from regional planning units to provide consideration for the conservation of important biodiversity regions, with additional oversight from the DLDLR with it's regional authority as outlined in the SPUMA Act.

Additionally, within the Waterberg District Bioregional Plan, a Biodiversity-Compatible Land use framework has been outlined for linking the CBA Map categories to land use planning and decision-making guidelines based on a set of land management objectives for achieving a desired ecological state.

**Comment by gubuntu** [comment]
thanks @zacharlie, very nicely structured and presented
