### ISSUE TITLE
19.2 Vegetation map or land cover map

### ISSUE THREAD

**Issue by gubuntu** [kartoza/WBR-SEMP#59]
A vegetation map or land cover map showing the principal habitats and land cover types of the proposed biosphere reserve should be provided, if available].

ref biosphere_reserve_nomination_form_2013_en.pdf

**Comment by seabilwe** [comment]
@gubuntu 
**UPDATE**
Below are the vegetation map and landcover maps:
Note: The legend for vegetation will be place in one map layout, except for the landcover map. I will try again to reduce the number of classes to match those in the study area.
**Vegetation**
![Vegetation](https://user-images.githubusercontent.com/56301949/97268376-7d086400-1834-11eb-8a03-4abf3496ea5f.png)
![Vegetation_2](https://user-images.githubusercontent.com/56301949/97268432-914c6100-1834-11eb-8565-66b1e26847ed.png)

**Landcover** 
![Landcover](https://user-images.githubusercontent.com/56301949/97268811-1fc0e280-1835-11eb-96eb-387a0c9fc17c.png)
![Landcover_2](https://user-images.githubusercontent.com/56301949/97268842-2e0efe80-1835-11eb-9a91-c08ecd8b58b3.png)

**Comment by gubuntu** [comment]
these are great but should be of the proposed reserve, not the AOI or DM. Only update if and when the process moves forward and we have a final boundary, for the LEDET process

**Comment by seabilwe** [comment]
@gubuntu I only can see the proposed WBR boundary from milestone 6 in the wbr postgis database and not the recent one you mentioned on the channel yesterday. Please give me access to it so that I may update the following below:

![image](https://user-images.githubusercontent.com/56301949/200170775-d3eb53f5-8c4b-42ae-936d-c16f8af77aec.png)
![WBR Landcover_2](https://user-images.githubusercontent.com/56301949/200170781-cae7abd0-0117-4cc3-9392-c4ed7dcc4e6a.png)

![WBR Vegetation](https://user-images.githubusercontent.com/56301949/200170811-a9828ef2-eacd-47ea-a64e-ee3b66fe23b4.png)
![WBR Vegetation_2](https://user-images.githubusercontent.com/56301949/200170825-488dca2c-be61-42bf-a565-b53d7c500c27.png)

**Comment by gubuntu** [comment]
@seabilwe I've granted you select permission on it. 

But I'm not sure you need to since I think the vegetation one is OK and I updated the landcover one in #52. But if you can, with the latest zones, please do (and I removed the images you copied in the above comment since they just repeated those above)

**Comment by seabilwe** [comment]
Updated vegetation Map (with the current AOI and without the proposed boundary)
![WBR Vegetation](https://user-images.githubusercontent.com/56301949/201646120-b180e07d-6854-4595-b227-97baeb9bb678.png)
![WBR Vegetation_2](https://user-images.githubusercontent.com/56301949/201646152-98922a0c-cd46-43ff-9d53-b970cc1503ec.png)
